language: java

jobs:
  include:
    - stage: "Tests"
      name: "SonarCloud tests"
      script:
        - mvn clean verify --file ./simple-api/pom.xml org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=devops-2020
      if: branch = main

    - stage: "Builds"
      name: "Build and Push to DockerHub"
      script:
        - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_LOGIN" --password-stdin
        - docker build -t "$DOCKERHUB_LOGIN"/tp-devops-epf:database database
        - docker build -t "$DOCKERHUB_LOGIN"/tp-devops-epf:simple-api simple-api
        - docker build -t "$DOCKERHUB_LOGIN"/tp-devops-epf:httpd httpd
        - docker build -t "$DOCKERHUB_LOGIN"/tp-devops-epf:front front
        - docker push "$DOCKERHUB_LOGIN"/tp-devops-epf:simple-api
        - docker push "$DOCKERHUB_LOGIN"/tp-devops-epf:database
        - docker push "$DOCKERHUB_LOGIN"/tp-devops-epf:httpd
        - docker push "$DOCKERHUB_LOGIN"/tp-devops-epf:front
      if: branch = main

    - stage: "Deploy"
      name: "Deploy on server"
      script:
        - ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml --vault-password-file $VAULT_PASS -e \"ci_user=$CI_REGISTRY_USER ci_password=$CI_REGISTRY_PASSWORD ci_registry=$CI_REGISTRY tag=$TAG\""
      if: branch = main

cache:
  directories:
    - $HOME/.m2

services:
  - docker

addons:
  sonarcloud:
    organization: "devops-epf"
    token: "$SONARCLOUD_TOKEN"
