all:
  vars:
    ansible_user: centos
    ansible_ssh_private_key_file: ~/Desktop/id_rsa
    my_db_user: usr
    my_db_password: pwd # should be encrypted with a vault
    my_db_name: db
    my_front_name: front
    my_db_hostname: database
    my_application_name: backend
    my_docker_repo: 17021997
    my_server: http://mlorrain.takima.cloud:8080
  children:
    prod:
      hosts: mlorrain.takima.cloud
